"""add new field role

Revision ID: 1ceb4a003c4b
Revises: 7026442dcfe7
Create Date: 2025-07-13 03:22:07.916679

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ceb4a003c4b"
down_revision: Union[str, Sequence[str], None] = "7026442dcfe7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.String(), nullable=False))
    op.alter_column("users", "age", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "users", "phone", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "phone", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("users", "age", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("users", "role")
    # ### end Alembic commands ###
